### ISSUE TITLE
添加一个合并的订阅地址

### ISSUE THREAD

**Issue by nanbowaner** [wdssmq/proxy_rsshub#1]
rt， 把输出的订阅合并，生成一个订阅地址。
好处是以后配置里添加新订阅后不用再处理了。

**Comment by wdssmq** [comment]
「折腾」Cloudflare Worker 反代 RSSHub\_电脑网络\_沉冰浮水：

[https://www.wdssmq.com/post/20100219897.html](https://www.wdssmq.com/post/20100219897.html "「折腾」Cloudflare Worker 反代 RSSHub\_电脑网络\_沉冰浮水")

现在推荐用这个 ↑
